"""CF22D: a chemistry functional with damped dispersion.

This file contains the original parameters of the CF22D functional [1].
The functional has 58 parameters (40 exchange + 9 LSDA correlation +
9 PBE-LSDA correlation) with the default HF mixing coefficient of 0.462806.

Generated by DFThub  https://dfthub.lrcwtech.com

Requirements: PySCF >= 2.4 (with libxc CF22D support)

Usage
-----
    from pyscf import gto, dft
    from CF22D_optimized import register_cf22d

    mol = gto.M(atom="H 0 0 0; H 0 0 0.74", basis="def2-qzvp")
    mf = dft.RKS(mol)
    mf.grids.level = 6
    register_cf22d(mf)
    mf.kernel()

References
----------
[1] Y. Liu, C. Zhang, Z. Liu, D. G. Truhlar, Y. Wang, X. He,
    Supervised Learning of a Chemistry Functional with Damped Dispersion,
    Nat. Comput. Sci., 2023, 3, 48-58.
"""

import numpy as np
from pyscf.dft import libxc

# 40 exchange coefficients  (Cx: _CC000 .. _CC302)
CX = np.array([
     3.420465997641110e-01, -6.403129726319901e-01, -9.343258286278120e-01,  2.548116332532230e-01,
     4.037942894981320e-01,  1.269312660000240e+00,  8.550102386275800e-02, -5.210700505353760e+00,
    -4.877609897602050e+00, -8.107937437626570e-01,  3.200067528069070e+00, -2.084116683362500e+00,
    -3.442955759357800e+00, -6.584525141174520e+00,  4.311580561114060e+00,  4.001780465506710e+00,
    -5.068257715480800e+00, -4.609538322325340e+00,  3.666974512750690e-01,  1.688404715603940e+00,
     1.132276274126880e+00, -6.644212396547720e-01, -8.542839602750379e-01,  2.228546690696300e+00,
     7.428226613038940e+00,  3.424630827360860e+00, -1.503891451116870e-01, -1.702216036299310e+00,
    -1.721828984322240e+00,  3.449962934107250e+00, -3.510995342270110e-01, -1.290159050757220e+00,
     2.296377003659940e+00, -1.449908779871820e+00, -1.036610748098920e+00,  2.386536009979160e+00,
     8.631845365492721e+00,  5.261947471262800e-02, -1.119462650428560e+00, -3.091283450748370e+00,
])

# 9 LSDA correlation coefficients  (Cy: _a0 .. _a8)
CY = np.array([
     8.725507563372000e-01,  4.468998640960900e-01,  4.491910770052130e+00, -9.931144521225890e-01,
    -2.726339657477250e+00, -1.936735776514450e-01,  4.431633587771830e-01, -2.310484724823420e+00,
     2.064573581116490e-01,
])

# 9 PBE-LSDA correlation coefficients  (Cz: _b0 .. _b8)
CZ = np.array([
     8.854855109687830e-01, -1.209725372266990e+00,  5.453278568094860e+00, -3.151355204738420e-01,
    -3.175066008038980e+00,  3.105458838276020e+00, -1.385493176417390e+00, -9.015986018178800e-02,
     2.427372033636820e+00,
])

# HF exact-exchange mixing coefficient
HF_COEFF = 0.462806


def register_cf22d(mf, name="cf22d_custom"):
    """Register the CF22D functional and apply it to *mf*.

    Parameters
    ----------
    mf : pyscf.dft.rks.RKS or pyscf.dft.uks.UKS
        A PySCF mean-field object.
    name : str, optional
        Internal name for the custom functional (default: "cf22d_custom").

    Returns
    -------
    mf : the same mean-field object with xc set to the CF22D functional.
    """
    x_params = np.zeros(41)
    x_params[:40] = CX
    x_params[40] = HF_COEFF

    c_params = np.zeros(24)
    c_params[:9] = CY
    c_params[12:21] = CZ

    name = name.lower()
    libxc.register_custom_functional_(
        name,
        "CF22D,CF22D",
        ext_params={340: x_params, 341: c_params},
    )
    mf.xc = name
    return mf


if __name__ == "__main__":
    from pyscf import gto, dft

    mol = gto.M(atom="H 0 0 0; H 0 0 0.74", basis="def2-qzvp", verbose=4)
    mf = dft.RKS(mol)
    mf.grids.level = 6
    register_cf22d(mf)
    mf.kernel()
    print(f"Total energy: {mf.e_tot:.10f} Hartree")
