"""CF22D: a chemistry functional with damped dispersion.

This file contains the original parameters of the CF22D functional [1]
and can read optimized parameters from a DFThub `Parameters` file.
The functional has 58 parameters (40 exchange + 9 LSDA correlation +
9 PBE-LSDA correlation) with the default HF mixing coefficient of 0.462806.
Following the current PySCF CF22D convention, D3 zero-damping dispersion
is enabled through the `cf22d` D3 parameter set.

Generated by DFThub  https://dfthub.lrcwtech.com

Requirements: PySCF >= 2.13.1 (with libxc CF22D support) and pyscf-dispersion

Usage
-----
    from pyscf import gto, dft
    from CF22D_optimized_example import register_cf22d

    mol = gto.M(atom="H 0 0 0; H 0 0 0.74", basis="def2-qzvp")
    mf = dft.RKS(mol)
    mf.grids.level = 6
    register_cf22d(mf)
    mf.kernel()

References
----------
[1] Y. Liu, C. Zhang, Z. Liu, D. G. Truhlar, Y. Wang, X. He,
    Supervised Learning of a Chemistry Functional with Damped Dispersion,
    Nat. Comput. Sci., 2023, 3, 48-58.
"""

from pathlib import Path

import numpy as np
from pyscf.dft import libxc

DEFAULT_PARAMETERS_PATH = Path(__file__).with_name("Parameters")
CF22D_D3_DISPERSION = "d3zero:cf22d"

CX_DIMS = [
    (0, 0, 6), (0, 1, 5), (0, 2, 4), (0, 3, 3),
    (1, 0, 5), (1, 1, 4), (1, 2, 3),
    (2, 0, 4), (2, 1, 3),
    (3, 0, 3),
]
CX_KEYS = [f"CX({i},{j},{k})" for i, j, n in CX_DIMS for k in range(n)]
CY_KEYS = [f"CY({i})" for i in range(9)]
CZ_KEYS = [f"CZ({i})" for i in range(9)]

# 40 exchange coefficients  (Cx: _CC000 .. _CC302)
CX = np.array([
     3.420465997641110e-01, -6.403129726319901e-01, -9.343258286278120e-01,  2.548116332532230e-01,
     4.037942894981320e-01,  1.269312660000240e+00,  8.550102386275800e-02, -5.210700505353760e+00,
    -4.877609897602050e+00, -8.107937437626570e-01,  3.200067528069070e+00, -2.084116683362500e+00,
    -3.442955759357800e+00, -6.584525141174520e+00,  4.311580561114060e+00,  4.001780465506710e+00,
    -5.068257715480800e+00, -4.609538322325340e+00,  3.666974512750690e-01,  1.688404715603940e+00,
     1.132276274126880e+00, -6.644212396547720e-01, -8.542839602750379e-01,  2.228546690696300e+00,
     7.428226613038940e+00,  3.424630827360860e+00, -1.503891451116870e-01, -1.702216036299310e+00,
    -1.721828984322240e+00,  3.449962934107250e+00, -3.510995342270110e-01, -1.290159050757220e+00,
     2.296377003659940e+00, -1.449908779871820e+00, -1.036610748098920e+00,  2.386536009979160e+00,
     8.631845365492721e+00,  5.261947471262800e-02, -1.119462650428560e+00, -3.091283450748370e+00,
])

# 9 LSDA correlation coefficients  (Cy: _a0 .. _a8)
CY = np.array([
     8.725507563372000e-01,  4.468998640960900e-01,  4.491910770052130e+00, -9.931144521225890e-01,
    -2.726339657477250e+00, -1.936735776514450e-01,  4.431633587771830e-01, -2.310484724823420e+00,
     2.064573581116490e-01,
])

# 9 PBE-LSDA correlation coefficients  (Cz: _b0 .. _b8)
CZ = np.array([
     8.854855109687830e-01, -1.209725372266990e+00,  5.453278568094860e+00, -3.151355204738420e-01,
    -3.175066008038980e+00,  3.105458838276020e+00, -1.385493176417390e+00, -9.015986018178800e-02,
     2.427372033636820e+00,
])

# HF exact-exchange mixing coefficient
HF_COEFF = 0.462806


def _compact_key(key):
    return "".join(key.split()).upper()


def _parse_float(raw):
    return float(raw.replace("D", "E").replace("d", "e"))


def read_cf22d_parameters(path=DEFAULT_PARAMETERS_PATH):
    """Read CF22D parameters from a DFThub `Parameters` file."""
    path = Path(path)
    values = {}
    hf_coeff = None

    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or "=" not in line:
            continue
        key, raw = [part.strip() for part in line.split("=", 1)]
        key = _compact_key(key)

        if key == "HF%":
            hf_coeff = _parse_float(raw) / 100.0
        elif key == "HF":
            hf_coeff = _parse_float(raw)
        elif key in CX_KEYS or key in CY_KEYS or key in CZ_KEYS:
            values[key] = _parse_float(raw)

    missing = [key for key in CX_KEYS + CY_KEYS + CZ_KEYS if key not in values]
    if missing or hf_coeff is None:
        missing_msg = ", ".join(missing[:5])
        if len(missing) > 5:
            missing_msg += ", ..."
        raise ValueError(f"Incomplete Parameters file {path}: missing {missing_msg or 'HF'}")

    cx = np.array([values[key] for key in CX_KEYS])
    cy = np.array([values[key] for key in CY_KEYS])
    cz = np.array([values[key] for key in CZ_KEYS])
    return cx, cy, cz, hf_coeff


def _get_parameters(parameters_path):
    if parameters_path is None:
        return CX, CY, CZ, HF_COEFF
    return read_cf22d_parameters(parameters_path)


def register_cf22d(mf, name="cf22d_custom", parameters_path=DEFAULT_PARAMETERS_PATH, with_d3=True):
    """Register the CF22D functional and apply it to *mf*.

    Parameters
    ----------
    mf : pyscf.dft.rks.RKS or pyscf.dft.uks.UKS
        A PySCF mean-field object.
    name : str, optional
        Internal name for the custom functional (default: "cf22d_custom").
    parameters_path : str or pathlib.Path or None, optional
        DFThub `Parameters` file. Use None to keep the embedded parameters.
    with_d3 : bool, optional
        Enable CF22D D3 zero-damping dispersion through PySCF.

    Returns
    -------
    mf : the same mean-field object with xc set to the CF22D functional.
    """
    cx, cy, cz, hf_coeff = _get_parameters(parameters_path)

    x_params = np.zeros(41)
    x_params[:40] = cx
    x_params[40] = hf_coeff

    c_params = np.zeros(24)
    c_params[:9] = cy
    c_params[12:21] = cz

    name = name.lower()
    libxc.register_custom_functional_(
        name,
        "CF22D,CF22D",
        ext_params={340: x_params, 341: c_params},
    )
    mf.xc = name
    mf.disp = CF22D_D3_DISPERSION if with_d3 else False
    return mf


if __name__ == "__main__":
    from pyscf import gto, dft

    mol = gto.M(atom="H 0 0 0; H 0 0 0.74", basis="def2-qzvp", verbose=4)
    mf = dft.RKS(mol)
    mf.grids.level = 6
    register_cf22d(mf)
    mf.kernel()
    print(f"Total energy: {mf.e_tot:.10f} Hartree")
